version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: hawkeye
      MONGO_INITDB_ROOT_PASSWORD: oKzC4umBBvj
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      MONGODB_URI: mongodb://hawkeye:oKzC4umBBvj@mongo:27017/


networks:
  default:
    name: hawkeye